export enum ContentElementType {
	FILE = 'file',
	DRAWING = 'drawing',
	LINK = 'link',
	RICH_TEXT = 'richText',
	EXTERNAL_TOOL = 'externalTool',
	COLLABORATIVE_TEXT_EDITOR = 'collaborativeTextEditor',
	VIDEO_CONFERENCE = 'videoConference',
	FILE_FOLDER = 'fileFolder',
	DELETED = 'deleted',
	H5P = 'h5p',
	POLL = 'poll',
	DEADLINE = 'deadline',
	CODE = 'code',
	FORMULA = 'formula',
	CHECKLIST = 'checklist',
	RECORDING = 'recording',
}
